---
title: "Script"
author: "Nicodemus"
date: "1/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

panggil library nya dulu

```{r}
rm(list=ls())
library(dplyr)
library(rvest)
library(tidytext)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(RSelenium)
library(XML)
library(tibble)
```
scraping data emiten dari idx.co.id 
```{r}
rD <- rsDriver(browser=c("firefox"))

driver <- rD$client
driver$navigate('https://www.idx.co.id/en-us/listed-companies/company-profiles/')

Sys.sleep(2)

input <- driver$findElement(using = "xpath","//*[@id='companyTable_length']/label/select")
input$clickElement()

Sys.sleep(2)

option <- driver$findElement(using = "xpath","/html/body/main/div[2]/div/div[2]/div/div[1]/label/select/option[4]")
option$clickElement()

Sys.sleep(2)

doc <- htmlParse(driver$getPageSource()[[1]])
x=readHTMLTable(doc)
emiten=x[["companyTable"]]

Sys.sleep(2)

for(i in 2:7){
  link = paste('/html/body/main/div[2]/div/div[2]/div/div[4]/span/a[',i,']',sep='')
  input <- driver$findElement(using = "xpath",link)
input$clickElement()

Sys.sleep(2)

doc <- htmlParse(driver$getPageSource()[[1]])
x=readHTMLTable(doc)
y=x[["companyTable"]]
emiten=rbind(y,emiten)
}

colnames(emiten)=c("no","code","name","listingdate")

emiten[,2]=as.character(emiten[,2])
```
list dari bank
```{r}
library(tibble)
emiten <- data.frame(x = c("BBCA","BBNI","BBRI","BMRI"), stringsAsFactors = FALSE)
```

scraping data per emiten
```{r}
# start the server and browser(you can use other browsers here)
rD <- rsDriver(browser=c("firefox"))

driver <- rD$client

i=1
url1 = paste('https://finance.yahoo.com/quote/',emiten[i,],'.JK/history?period1=1421798400&period2=1579564800&interval=1d&filter=history&frequency=1d',sep='')
driver$navigate(url1)

element <- driver$findElement("css", "body")
flag <- TRUE
counter <- 0
n <- 5
while(flag){
    counter <- counter + 1
    #compare the pagesource every n(n=5) time, since sometimes one scroll down doesn't render new content
    for(i in 1:n){
        element$sendKeysToElement(list("key"="page_down"))
        Sys.sleep(2)
    }
    if(exists("pagesource")){
        if(pagesource == driver$getPageSource()[[1]]){
            flag <- FALSE
            writeLines(paste0("Scrolled down ",n*counter," times.\n"))
        } else {
            pagesource <- driver$getPageSource()[[1]]
        }
    } else {
        pagesource <- driver$getPageSource()[[1]]
    }
}

doc <- htmlParse(driver$getPageSource()[[1]])
x=readHTMLTable(doc)
test=x[["NULL"]]
test$emiten=emiten[1,]

for(i in 2:4){
# navigate to an URL
  url1 = paste('https://finance.yahoo.com/quote/',emiten[i,],'.JK/history?period1=1421798400&period2=1579564800&interval=1d&filter=history&frequency=1d',sep='')
driver$navigate(url1)

element <- driver$findElement("css", "body")
flag <- TRUE
counter <- 0
n <- 5
while(flag){
    counter <- counter + 1
    #compare the pagesource every n(n=5) time, since sometimes one scroll down doesn't render new content
    for(i in 1:n){
        element$sendKeysToElement(list("key"="page_down"))
        Sys.sleep(2)
    }
    if(exists("pagesource")){
        if(pagesource == driver$getPageSource()[[1]]){
            flag <- FALSE
            writeLines(paste0("Scrolled down ",n*counter," times.\n"))
        } else {
            pagesource <- driver$getPageSource()[[1]]
        }
    } else {
        pagesource <- driver$getPageSource()[[1]]
    }
}

library(XML)
doc <- htmlParse(driver$getPageSource()[[1]])
x=readHTMLTable(doc)
y=x[["NULL"]]
y$emiten=emiten[i,]
test=rbind(y,test)
}

rm(rD)
gc()
```